### ISSUE TITLE
Ed25519 missing variables, invalid escape sequence, atrribute error? 

### ISSUE THREAD

**Issue by Lordsik** [ebellocchia/bip_utils#115]
Collecting ed25519-blake2b~=1.4
  Using cached ed25519-blake2b-1.4.tar.gz (871 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      C:\Users\Administrator\AppData\Local\Temp\2\pip-install-af2gumqq\ed25519-blake2b_327ee63b6
24a4e8f8100568441fc8aef\versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-af2gumqq\ed25519-blake2b_3
27ee63b624a4e8f8100568441fc8aef\setup.py", line 109, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-af2gumqq\ed25519-blake2b_3
27ee63b624a4e8f8100568441fc8aef\versioneer.py", line 1405, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-af2gumqq\ed25519-blake2b_3
27ee63b624a4e8f8100568441fc8aef\versioneer.py", line 1339, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-af2gumqq\ed25519-blake2b_3
27ee63b624a4e8f8100568441fc8aef\versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: '
RawConfigParser'?
      [end of output]
Python 3.12

**Comment by ebellocchia** [comment]
Hi, as you can see from the file names, I built the library for Python 3.11 at latest, so you cannot install the wheels for Python 3.12

**Comment by Lordsik** [comment]
Thanks Python 3.11.5 Works great
