### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by peanut0218** [ebellocchia/bip_utils#118]
Processing c:\downloads\bip_utils-2.9.0-py3-none-any.whl
Collecting cbor2~=5.1 (from bip-utils==2.9.0)
  Using cached cbor2-5.5.1-cp312-cp312-win_amd64.whl.metadata (6.1 kB)
Requirement already satisfied: coincurve<19.0.0,>=15.0.1 in c:\python312\lib\site-packages (from bip-utils==2.9.0) (18.0.0)
Collecting crcmod~=1.7 (from bip-utils==2.9.0)
  Using cached crcmod-1.7.tar.gz (89 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ecdsa~=0.15 in c:\python312\lib\site-packages (from bip-utils==2.9.0) (0.18.0)
Collecting ed25519-blake2b~=1.4 (from bip-utils==2.9.0)
  Using cached ed25519-blake2b-1.4.tar.gz (871 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      C:\Users\AppData\Local\Temp\pip-install-3pibhw5z\ed25519-blake2b_42e85bd54dd245cfbc9748b33d7e406b\versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\AppData\Local\Temp\pip-install-3pibhw5z\ed25519-blake2b_42e85bd54dd245cfbc9748b33d7e406b\setup.py", line 109, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\AppData\Local\Temp\pip-install-3pibhw5z\ed25519-blake2b_42e85bd54dd245cfbc9748b33d7e406b\versioneer.py", line 1405, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\AppData\Local\Temp\pip-install-3pibhw5z\ed25519-blake2b_42e85bd54dd245cfbc9748b33d7e406b\versioneer.py", line 1339, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\AppData\Local\Temp\pip-install-3pibhw5z\ed25519-blake2b_42e85bd54dd245cfbc9748b33d7e406b\versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by peanut0218** [comment]
My python version is 3.12.1

**Comment by ebellocchia** [comment]
Hi, it's not yet compatible with 3.12, you can use 3.11

**Comment by ebellocchia** [comment]
The package was fixed, it can be installed via pip
