### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by Noname400** [ebellocchia/bip_utils#42]
jo@Noname-Home:~/bip_utils$ pip install . --install-option="--coincurve=0"
/usr/lib/python3/dist-packages/pip/_internal/commands/install.py:255: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Processing /home/jo/bip_utils
Requirement already satisfied: coincurve<16.0.0,>=15.0.1 in /usr/local/lib/python3.8/dist-packages (from bip-utils==2.1.0) (15.0.1)
Collecting crcmod~=1.7
  Using cached crcmod-1.7.tar.gz (89 kB)
Collecting ecdsa~=0.15
  Using cached ecdsa-0.17.0.tar.gz (158 kB)
Collecting ed25519-blake2b~=1.4
  Using cached ed25519-blake2b-1.4.tar.gz (871 kB)
Collecting py-sr25519-bindings<2.0.0,>=0.1.3
  Using cached py_sr25519_bindings-0.1.4.tar.gz (13 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-313w608l/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.12,<0.13'
       cwd: None
  Complete output (58 lines):
  Collecting maturin<0.13,>=0.12
    Using cached maturin-0.12.5.tar.gz (138 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting toml~=0.10.0
    Using cached toml-0.10.2.tar.gz (22 kB)
  Skipping wheel build for toml, due to binaries being disabled for it.
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmp58sd8_yv build_wheel /tmp/tmpmnhimxtf
         cwd: /tmp/pip-install-l0wub0gb/maturin
    Complete output (36 lines):
    running bdist_wheel
    running build
    installing to build/bdist.linux-x86_64/wheel
    running install
    Traceback (most recent call last):
      File "/tmp/tmp58sd8_yv", line 280, in <module>
        main()
      File "/tmp/tmp58sd8_yv", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmp58sd8_yv", line 204, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/tmp/pip-build-env-31bqagyx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/tmp/pip-build-env-31bqagyx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
        self.run_setup()
      File "/tmp/pip-build-env-31bqagyx/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 115, in <module>
        setup(
      File "/tmp/pip-build-env-31bqagyx/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-31bqagyx/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
        self.run_command('install')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "setup.py", line 57, in run
        raise RuntimeError(
    RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-313w608l/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.12,<0.13' Check the logs for full command output.

**Comment by ebellocchia** [comment]
Hi,
you have to install Rust in order to use the sr25519 library.

Regards,
Emanuele
