### ISSUE TITLE
failed to generate address on windows

### ISSUE THREAD

**Issue by spankders** [ebellocchia/bip_utils#49]
this code work fine on ubuntu but when i try to run it on window i get the error shown below

Code Snippet:
```
from bip_utils import Bip44Coins, Bip44, Bip39SeedGenerator, Bip39MnemonicGenerator, Bip39WordsNum

mnemonic = Bip39MnemonicGenerator().FromWordsNumber(Bip39WordsNum.WORDS_NUM_24)
seed_bytes = Bip39SeedGenerator(mnemonic).Generate()
bip44_def_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
print(bip44_def_ctx.PublicKey().ToAddress())
```

The Error:

```
Traceback (most recent call last):
  File "C:\generate.py", line 5, in <module>
    bip44_def_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
  File "C:\Python310\lib\enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: SOLANA
```

**Comment by ebellocchia** [comment]
Hi,
the only reason for the error is that you have an old version of the library installed, otherwise that code shall work.
Can you check the installed version?

Regards,
Emanuele

**Comment by spankders** [comment]
you are right i just updated to the latest version and it worked thanks
